load:
  duration: 180s
  rate: 1000
  concurrency: 20
servers:
- name: Sangria
  endpoint: http://localhost:8081/graphql
  run:
    command: sbt run
    cwd: servers/jvm/sangria-akka/
  warmup:
    concurrency: 5
    duration: 20s
- name: GraphQL-java
  endpoint: http://localhost:8080/graphql
  run:
    command: ./gradlew bootRun
    cwd: servers/jvm/graphql-java/
  warmup:
    concurrency: 5
    duration: 20s

- name: Lacinia
  endpoint: http://localhost:3000/graphql
  run:
    command: lein ring server-headless
    cwd: servers/jvm/lacinia/
  warmup:
    concurrency: 5
    duration: 10s

- name: Graphene
  endpoint: http://localhost:8080/graphql
  run:
    command: python3 app.py
    cwd: servers/python/
  warmup:
    concurrency: 5
    duration: 20s

- name: GraphQL-js
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node/graphql-js
  warmup:
    concurrency: 5
    duration: 20s

- name: GraphQL-JIT
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node/graphql-jit/
  warmup:
    concurrency: 5
    duration: 20s

- name: Graph Gophers
  endpoint: http://localhost:8082/graphql
  run:
    command: go run schema.go server.go
    cwd: servers/golang/graph-gophers/
  warmup:
    concurrency: 5
    duration: 20s

- name: Graphql-Go
  endpoint: http://localhost:8083/graphql
  run:
    command: go run server.go
    cwd: servers/golang/graphql-go/
  warmup:
    concurrency: 5
    duration: 20s

queries:
- name: Basic
  filename: queries/basic.graphql
  expectedResultFilename: queries/basic.json

- name: Scalar List
  filename: queries/scalar_list.graphql
  expectedResultFilename: queries/scalar_list.json

- name: Object List
  filename: queries/object_list.graphql
  expectedResultFilename: queries/object_list.json

- name: Interface List
  filename: queries/interface_list.graphql
#  expectedResultFilename: queries/interface_list.json

- name: Introspection
  filename: queries/introspection.graphql
#  expectedResultFilename: queries/introspection.json
