servers:
- name: Sangria
  endpoint: http://localhost:8081/graphql
  run:
    command: sbt run
    cwd: servers/sangria-akka/
    startupTime: 15s
  warmup:
    concurrency: 1
    duration: 10s

- name: Graphene
  endpoint: http://localhost:8080/graphql
  run:
    command: python3 app.py
    cwd: servers/japronto-graphene/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Graphene+Quiver
  endpoint: http://localhost:8080/quiver
  run:
    command: python3 app.py
    cwd: servers/japronto-graphene/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Node Express
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node-express/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Node Micro
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node-micro/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Node JIT - No leaf
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js disable-leaf
    cwd: servers/node-jit/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Node JIT - Leaf
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node-jit/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Go
  endpoint: http://localhost:8082/query
  run:
    command: go run schema.go server.go
    cwd: servers/go/
    startupTime: 15s
  warmup:
    concurrency: 1
    duration: 5s

queries:
- name: Basic
  filename: queries/basic.graphql
  expectedResultFilename: queries/basic.json

- name: Scalar List
  filename: queries/scalar_list.graphql
  expectedResultFilename: queries/scalar_list.json

- name: Object List
  filename: queries/object_list.graphql
  expectedResultFilename: queries/object_list.json

#- name: Interface List
#  filename: queries/interface_list.graphql
#  expectedResultFilename: queries/interface_list.json

- name: Introspection
  filename: queries/introspection.graphql
#  expectedResultFilename: queries/introspection.json
