load:
  duration: 180s
  rate: 1000
  concurrency: 20
servers:
- name: JSON.stringify
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js
    cwd: servers/node-jit/
  warmup:
    concurrency: 1
    duration: 5s

- name: fast-json-stringify
  endpoint: http://localhost:4000/graphql
  run:
    command: node app.js fast-json
    cwd: servers/node-jit/
  warmup:
    concurrency: 5
    duration: 20s

queries:
- name: Basic
  filename: queries/basic.graphql
  expectedResultFilename: queries/basic.json

- name: Scalar List
  filename: queries/scalar_list.graphql
  expectedResultFilename: queries/scalar_list.json

- name: Object List
  filename: queries/object_list.graphql
  expectedResultFilename: queries/object_list.json

- name: Interface List
  filename: queries/interface_list.graphql
#  expectedResultFilename: queries/interface_list.json

- name: Introspection
  filename: queries/introspection.graphql
#  expectedResultFilename: queries/introspection.json
